doctrine:
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            default:
                auto_mapping: true

doctrine_migrations:
    connection: default
    migrations_paths:
        'SeoBundle\Migrations': '@SeoBundle/Migrations'
